let foods = [
  { id: 1, name: "Haferflocken", category: "breakfast", meal: "Frühstück", calories: 372, protein: 13.5, carbs: 58.7, fat: 7, emoji: "🥣", portion: "pro 100 g" },
  { id: 2, name: "Banane", category: "breakfast", meal: "Frühstück", calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, emoji: "🍌", portion: "pro 100 g" },
  { id: 3, name: "Hähnchenbrust", category: "lunch", meal: "Mittagessen", calories: 110, protein: 23.1, carbs: 0, fat: 1.2, emoji: "🍗", portion: "pro 100 g" },
  { id: 4, name: "Avocado", category: "lunch", meal: "Mittagessen", calories: 160, protein: 2, carbs: 8.5, fat: 14.7, emoji: "🥑", portion: "pro 100 g" },
  { id: 5, name: "Griechischer Joghurt", category: "snack", meal: "Snack", calories: 97, protein: 9, carbs: 3.6, fat: 5, emoji: "🥛", portion: "pro 100 g" },
  { id: 6, name: "Mandeln", category: "snack", meal: "Snack", calories: 579, protein: 21.2, carbs: 21.6, fat: 49.9, emoji: "🥜", portion: "pro 100 g" },
  { id: 7, name: "Lachsfilet", category: "dinner", meal: "Abendessen", calories: 208, protein: 20.4, carbs: 0, fat: 13.4, emoji: "🐟", portion: "pro 100 g" },
  { id: 8, name: "Süßkartoffel", category: "dinner", meal: "Abendessen", calories: 86, protein: 1.6, carbs: 20.1, fat: 0.1, emoji: "🍠", portion: "pro 100 g" }
];
foods.push({ id: 9, name: "Ei", category: "breakfast", meal: "Frühstück", calories: 143, protein: 12.6, carbs: 0.7, fat: 9.5, emoji: "🥚", portion: "pro 100 g", pieceWeight: 60 }, { id: 10, name: "Toast", category: "breakfast", meal: "Frühstück", calories: 266, protein: 8.5, carbs: 49, fat: 3.2, emoji: "🍞", portion: "pro 100 g", pieceWeight: 30 }, { id: 11, name: "Butter", category: "breakfast", meal: "Frühstück", calories: 717, protein: 0.9, carbs: 0.1, fat: 81, emoji: "🧈", portion: "pro 100 g" });
const defaultEntries = [{ foodId: 2, amount: 120, meal: "Frühstück" }, { foodId: 5, amount: 200, meal: "Snack" }, { foodId: 3, amount: 180, meal: "Mittagessen" }];
function localIsoDate(date = new Date()) { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, "0"); const day = String(date.getDate()).padStart(2, "0"); return `${year}-${month}-${day}`; }
const todayIso = localIsoDate();
const yesterdayIso = localIsoDate(new Date(Date.now() - 86400000));
const hasDateMigration = localStorage.getItem("nutrify-date-migration-v2");
const storedEntries = JSON.parse(localStorage.getItem("nutrify-entries") || "null") || defaultEntries.map((entry) => ({ ...entry, date: yesterdayIso }));
if (!hasDateMigration && storedEntries.length) { storedEntries.forEach((entry) => { if (!entry.date || entry.date === todayIso) entry.date = yesterdayIso; }); localStorage.setItem("nutrify-date-migration-v2", "1"); }
let allEntries = storedEntries.map((entry) => ({ ...entry, date: entry.date || yesterdayIso }));
let entries = allEntries;
let goal = Number(localStorage.getItem("nutrify-goal")) || 2000;
let shownMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
let supabaseClient = null;
let currentUser = null;
let authModeLogin = true;
let remoteMode = false;
let pendingEntries = JSON.parse(localStorage.getItem("nutrify-pending-entries") || "[]");
const $ = (selector) => document.querySelector(selector);
let selectedDate = todayIso;
const config = () => ({ url: window.NUTRIFY_CONFIG?.url || localStorage.getItem("nutrify-supabase-url"), key: window.NUTRIFY_CONFIG?.key || localStorage.getItem("nutrify-supabase-key") });
const foodForEntry = (entry) => entry.food || foods.find((food) => food.id === entry.foodId) || { name: "Lebensmittel", calories: 0, emoji: "🍽️" };
const kcalFor = (entry) => Math.round((foodForEntry(entry).calories * entry.amount) / 100);
const saveEntries = () => localStorage.setItem("nutrify-entries", JSON.stringify(allEntries));
function formatDate(date) { return new Intl.DateTimeFormat("de-DE", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(`${date}T12:00:00`)); }
function isPastDate(date) { return date < todayIso; }
function updateAddControls() { document.querySelectorAll("[data-open-log], .food-add").forEach((button) => { button.disabled = isPastDate(selectedDate); button.title = isPastDate(selectedDate) ? "Vergangene Tage können nicht bearbeitet werden" : "Eintrag hinzufügen"; }); }
function renderDaySummary() { const total = entries.reduce((sum, entry) => sum + kcalFor(entry), 0); $("#summary-date").textContent = formatDate(selectedDate); $("#summary-kcal").textContent = `${total.toLocaleString("de-DE")} kcal`; $("#summary-entries").textContent = entries.length; updateAddControls(); renderMacros(); }
function renderMacros() { const totals = entries.reduce((result, entry) => { const food = foodForEntry(entry); const factor = entry.amount / 100; result.protein += (food.protein || 0) * factor; result.carbs += (food.carbs || 0) * factor; result.fat += (food.fat || 0) * factor; return result; }, { protein: 0, carbs: 0, fat: 0 }); const targets = { protein: 120, carbs: 220, fat: 65 }; const rows = [{ key: "protein", label: "Protein", icon: "P", color: "#ed836c", className: "protein" }, { key: "carbs", label: "Kohlenhydrate", icon: "K", color: "#7a9f87", className: "carbs" }, { key: "fat", label: "Fette", icon: "F", color: "#eabf66", className: "fat" }]; $("#macro-list").innerHTML = rows.map((row) => { const value = Math.round(totals[row.key]); const percentage = Math.min(100, Math.round(value / targets[row.key] * 100)); return `<div class="macro-row"><div class="macro-label"><span class="macro-icon ${row.className}">${row.icon}</span><span>${row.label}<small>${value} / ${targets[row.key]} g</small></span></div><div class="progress"><span style="width:${percentage}%; background:${row.color}"></span></div><strong>${percentage}%</strong></div>`; }).join(""); }
function setSelectedDate(date) { selectedDate = date; localStorage.setItem("nutrify-selected-date", date); $("#selected-date").value = date; $("#current-date-label").textContent = date === todayIso ? `Heute · ${formatDate(date)}` : formatDate(date); $("#calorie-date-label").textContent = formatDate(date); $("#entries-date-label").textContent = formatDate(date); $("#macro-date").textContent = new Intl.DateTimeFormat("de-DE", { day: "numeric", month: "short" }).format(new Date(`${date}T12:00:00`)); $("#calendar-grid").querySelectorAll("[data-date]").forEach((day) => day.classList.toggle("selected", day.dataset.date === date)); if (remoteMode) loadRemoteData().then(() => { renderDashboard(); renderWeek(); renderDaySummary(); }).catch(() => setSyncStatus("offline", "Offline gespeichert")); else { entries = allEntries.filter((entry) => entry.date === selectedDate); renderDashboard(); renderWeek(); renderDaySummary(); } }
function shiftSelectedDate(amount) { const date = new Date(`${selectedDate}T12:00:00`); date.setDate(date.getDate() + amount); setSelectedDate(localIsoDate(date)); }
function setSyncStatus(state, label) { const status = $("#sync-status"); if (!status) return; status.className = `sync-status ${state}`; $("#sync-label").textContent = label; }
async function withRetry(task, attempts = 3) { let lastError; for (let attempt = 0; attempt < attempts; attempt += 1) { try { return await Promise.race([task(), new Promise((_, reject) => window.setTimeout(() => reject(new Error("Zeitüberschreitung der Online-Verbindung")), 8000))]); } catch (error) { lastError = error; if (attempt < attempts - 1) await new Promise((resolve) => window.setTimeout(resolve, 500 * (attempt + 1))); } } throw lastError; }

function setAuthMessage(message, error = false) { const element = $("#auth-message"); element.textContent = message; element.classList.toggle("error", error); }
function friendlyAuthError(error) { const message = error?.message || "Unbekannter Fehler"; if (message.toLowerCase().includes("invalid api key")) return "Der Supabase-Schlüssel ist ungültig. Bitte unter Project Settings → API den Publishable key kopieren."; if (message.toLowerCase().includes("invalid login credentials")) return "E-Mail oder Passwort ist falsch."; if (message.toLowerCase().includes("email not confirmed")) return "Bitte bestätige zuerst den Link in deiner E-Mail."; if (message.toLowerCase().includes("user already registered")) return "Für diese E-Mail gibt es bereits ein Konto. Nutze den Login."; return message; }
function showSetup() { $("#auth-screen").hidden = false; $("#auth-screen").classList.remove("is-leaving"); $("#app-shell").hidden = true; $("#setup-state").hidden = false; $("#login-state").hidden = true; document.body.classList.add("auth-open"); }
function showLogin(message = "") { $("#auth-screen").hidden = false; $("#auth-screen").classList.remove("is-leaving"); $("#app-shell").hidden = true; $("#setup-state").hidden = true; $("#login-state").hidden = false; document.body.classList.add("auth-open"); setAuthMessage(message); }
function hideAuthScreen() { $("#auth-screen").classList.add("is-leaving"); document.body.classList.remove("auth-open"); window.setTimeout(() => { $("#auth-screen").hidden = true; $("#auth-screen").classList.remove("is-leaving"); }, 360); }
async function initialiseAuth() { const saved = config(); if (!saved.url || !saved.key) return showSetup(); try { supabaseClient = window.supabase.createClient(saved.url, saved.key); } catch (error) { showSetup(); return setAuthMessage(friendlyAuthError(error), true); } const { data, error } = await supabaseClient.auth.getSession(); if (error) { showSetup(); return setAuthMessage(friendlyAuthError(error), true); } if (data.session) return enterApp(data.session.user); showLogin("Verbindung erfolgreich. Erstelle jetzt dein NUTRIFY-Konto oder logge dich ein."); supabaseClient.auth.onAuthStateChange((event, session) => { if (event === "SIGNED_IN" && session) enterApp(session.user); if (event === "SIGNED_OUT") showLogin("Du wurdest ausgeloggt."); }); }
async function enterApp(user) { currentUser = user; remoteMode = true; $("#app-shell").hidden = false; $("#profile-email").textContent = user.email; $("#account-email").textContent = user.email; $("#profile-avatar").textContent = (user.email || "NU").slice(0, 2).toUpperCase(); hideAuthScreen(); try { await loadRemoteData(); if (await syncPendingEntries()) await loadRemoteData(); } catch (error) { setSyncStatus("offline", "Offline gespeichert"); showToast(`Online-Daten nicht erreichbar: ${friendlyAuthError(error)}`); } renderDashboard(); renderWeek(); renderDaySummary(); }
async function loadRemoteData() { setSyncStatus("syncing", "Verbindung wird geprüft ..."); const [profileResult, entryResult] = await withRetry(() => Promise.all([supabaseClient.from("profiles").select("daily_goal,display_name").eq("id", currentUser.id).maybeSingle(), supabaseClient.from("food_entries").select("id,food_name,food_brand,product_code,calories_per_100g,amount_grams,meal").eq("eaten_on", selectedDate).order("created_at")])); if (profileResult.data?.daily_goal) goal = profileResult.data.daily_goal; if (profileResult.data?.display_name) { $("#profile-name").textContent = profileResult.data.display_name; $("#account-name").value = profileResult.data.display_name; } if (!entryResult.error) entries = (entryResult.data || []).map((entry) => ({ id: entry.id, amount: entry.amount_grams, meal: entry.meal, date: selectedDate, food: { id: `remote-${entry.id}`, name: entry.food_name, brand: entry.food_brand, calories: entry.calories_per_100g, emoji: "🍽️" } })); else entries = allEntries.filter((entry) => entry.date === selectedDate); localStorage.setItem("nutrify-goal", goal); setSyncStatus("", entryResult.error ? "Online verbunden · lokal" : "Online-Sync aktiv"); }
async function saveRemoteEntry(food, amount, meal) { const fullEntry = { user_id: currentUser.id, food_name: food.name, food_brand: food.brand || null, product_code: food.code || null, calories_per_100g: food.calories, amount_grams: amount, meal, eaten_on: selectedDate }; const result = await withRetry(() => supabaseClient.from("food_entries").insert(fullEntry)); if (result.error) throw result.error; setSyncStatus("", "Online-Sync aktiv"); }
async function syncPendingEntries() { if (!pendingEntries.length) return false; const remaining = []; for (const entry of pendingEntries) { try { await saveRemoteEntry(entry.food, entry.amount, entry.meal); } catch { remaining.push(entry); } } const changed = remaining.length !== pendingEntries.length; pendingEntries = remaining; localStorage.setItem("nutrify-pending-entries", JSON.stringify(pendingEntries)); return changed; }
async function deleteEntry(entry) { if (remoteMode && entry.id) { const { error } = await supabaseClient.from("food_entries").delete().eq("id", entry.id); if (error) { entries = entries.filter((item) => item !== entry); saveEntries(); showToast("Lokal entfernt; Online-Sync fehlgeschlagen"); } else await loadRemoteData(); } else { allEntries = allEntries.filter((item) => item !== entry); entries = allEntries.filter((item) => item.date === selectedDate); saveEntries(); } renderDashboard(); showToast("Eintrag entfernt"); }
function renderDashboard() { const total = entries.reduce((sum, entry) => sum + kcalFor(entry), 0); $("#calories-total").textContent = total.toLocaleString("de-DE"); $("#goal-label").textContent = goal.toLocaleString("de-DE"); $("#consumed-label").textContent = `${total.toLocaleString("de-DE")} kcal`; $("#remaining-label").textContent = `${Math.max(0, goal - total).toLocaleString("de-DE")} kcal`; const percentage = Math.min(100, total / goal * 100); $("#calorie-ring").style.background = `conic-gradient(#e3f1d9 0 ${percentage}%, rgba(255,255,255,.18) ${percentage}% 100%)`; $("#entries-list").innerHTML = entries.map((entry, index) => { const food = foodForEntry(entry); return `<div class="entry"><div class="entry-info"><span class="entry-icon">${food.emoji}</span><span><strong>${food.brand ? `${food.brand} ` : ""}${food.name}</strong><small>${entry.meal} · ${entry.amount} g</small></span></div><span class="entry-calories">${kcalFor(entry)} kcal</span><button type="button" class="text-link remove-entry" data-index="${index}" aria-label="Eintrag löschen">×</button></div>`; }).join(""); document.querySelectorAll(".remove-entry").forEach((button) => button.addEventListener("click", () => deleteEntry(entries[Number(button.dataset.index)] || button.dataset.index))); }
function renderWeek() { const values = [1680, 2010, 1880, 2140, entries.reduce((sum, entry) => sum + kcalFor(entry), 0), 0, 0]; $("#week-chart").innerHTML = values.map((value, index) => `<div class="bar-wrap"><div class="bar ${index === 4 ? "today" : ""}" style="height:${Math.max(10, Math.min(100, value / goal * 100))}%"></div><span>${["Sa", "So", "Mo", "Di", "Heute", "Do", "Fr"][index]}</span></div>`).join(""); }
function renderFoods() { const search = $("#food-search").value.trim().toLowerCase(); const filtered = foods.filter((food) => !search || food.name.toLowerCase().includes(search) || (food.brand && food.brand.toLowerCase().includes(search))); $("#food-grid").innerHTML = filtered.length ? filtered.map((food) => `<article class="food-card"><div class="food-card-top"><span class="food-emoji">${food.emoji || "📦"}</span><div><strong>${food.name}</strong><small>${food.brand || "Keine Marke angegeben"}</small></div><button type="button" class="text-link food-add" data-food-id="${food.id}" aria-label="Eintrag hinzufügen">+</button></div><div class="food-card-bottom"><span><strong>${food.calories} kcal</strong> / 100 g</span></div><div class="food-card-macros"><span>Protein ${Number(food.protein || 0).toFixed(1)} g</span><span>KH ${Number(food.carbs || 0).toFixed(1)} g</span><span>Fett ${Number(food.fat || 0).toFixed(1)} g</span></div></article>`).join("") : `<span class="recipe-chip"><small>Keine Lebensmittel gefunden</small></span>`; document.querySelectorAll("[data-food-id]").forEach((button) => button.addEventListener("click", () => openLog(button.dataset.foodId))); }
function calculateGoal() { const age = Number($("#goal-age").value); const height = Number($("#goal-height").value); const weight = Number($("#goal-weight").value); const activity = Number($("#goal-activity").value); const sex = $("#goal-sex").value; const base = 10 * weight + 6.25 * height - 5 * age + (sex === "male" ? 5 : -161); const direction = $("#goal-direction").value; const adjustment = direction === "lose" ? -350 : direction === "gain" ? 300 : 0; $("#calculated-goal").textContent = `${Math.max(1200, Math.round(base * activity + adjustment)).toLocaleString("de-DE")} kcal`; }
function renderRecipes() { const recipes = JSON.parse(localStorage.getItem("nutrify-recipes") || "[]"); $("#recipe-list").innerHTML = recipes.length ? recipes.map((recipe) => `<button class="recipe-chip" type="button" data-recipe-calories="${recipe.calories}"><strong>${recipe.name}</strong><small>${recipe.calories} kcal · 1 Portion</small></button>`).join("") : `<span class="recipe-chip"><small>Noch keine Rezepte gespeichert</small></span>`; document.querySelectorAll("[data-recipe-calories]").forEach((button) => button.addEventListener("click", () => showToast(`${button.dataset.recipeCalories} kcal pro Portion`))); }
function toggleFavorite(foodId) { const favorites = JSON.parse(localStorage.getItem("nutrify-favorites") || "[]"); const index = favorites.indexOf(String(foodId)); if (index >= 0) favorites.splice(index, 1); else favorites.push(String(foodId)); localStorage.setItem("nutrify-favorites", JSON.stringify(favorites)); showToast(index >= 0 ? "Favorit entfernt" : "Zu Favoriten hinzugefügt"); }
function runQuickEntry() { const text = $("#quick-entry-input").value.trim().toLowerCase(); if (!text) return; const parts = text.split("+").map((part) => part.trim()); const matches = parts.map((part) => { const number = Number(part.match(/^\d+/)?.[0] || 1); const food = foods.find((item) => part.replace(/^\d+\s*/, "").includes(item.name.toLowerCase()) || (item.name === "Ei" && part.includes("eier"))); return food ? { food, amount: number * (food.pieceWeight || 100) } : null; }).filter(Boolean); if (!matches.length) return showToast("Kein passendes Lebensmittel gefunden"); if (isPastDate(selectedDate)) return showToast("Vergangene Tage können nicht bearbeitet werden"); matches.forEach(({ food, amount }) => allEntries.push({ foodId: food.id, amount, meal: "Snack", food, date: selectedDate })); entries = allEntries.filter((entry) => entry.date === selectedDate); saveEntries(); renderDashboard(); renderDaySummary(); $("#quick-entry-input").value = ""; showToast(`${matches.length} Lebensmittel hinzugefügt`); }
async function searchOnlineFoods() { const query = $("#food-search").value.trim(); if (query.length < 3) return; const cacheKey = `nutrify-food-search-${query.toLowerCase()}`; try { const response = await withRetry(() => fetch(`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(query)}&search_simple=1&action=process&json=1&page_size=30&fields=code,product_name,brands,nutriments,nutrition_grades,image_url,quantity`), 2); if (!response.ok) throw new Error("Open Food Facts nicht erreichbar"); const data = await response.json(); const onlineFoods = (data.products || []).filter((item) => item.product_name && (item.nutriments?.["energy-kcal_100g"] || item.nutriments?.energy_100g)).map((item) => ({ id: `off-${item.code}`, name: item.product_name, brand: item.brands || "", category: "all", meal: "Snack", calories: Math.round(item.nutriments["energy-kcal_100g"] || item.nutriments.energy_100g / 4.184), protein: item.nutriments.proteins_100g || 0, carbs: item.nutriments.carbohydrates_100g || 0, fat: item.nutriments.fat_100g || 0, fiber: item.nutriments.fiber_100g || 0, sugar: item.nutriments.sugars_100g || 0, salt: item.nutriments.salt_100g || 0, emoji: "📦", portion: "pro 100 g", nutrientBasis: "pro 100 g", source: "Open Food Facts", reference: item.code, code: item.code, image: item.image_url || "", nutriScore: item.nutrition_grades || "", quantity: item.quantity || "" })); localStorage.setItem(cacheKey, JSON.stringify(onlineFoods)); foods = [...foods.filter((food) => !String(food.id).startsWith("off-")), ...onlineFoods]; renderFoods(); } catch (error) { console.error("Open Food Facts Suche:", error); const cached = localStorage.getItem(cacheKey); if (cached) { foods = [...foods.filter((food) => !String(food.id).startsWith("off-")), ...JSON.parse(cached)]; renderFoods(); } else { showToast("Keine Online-Lebensmittel gefunden"); } } }
    
    

function renderCalendar() { const year = shownMonth.getFullYear(); const month = shownMonth.getMonth(); const firstDay = (new Date(year, month, 1).getDay() + 6) % 7; const days = new Date(year, month + 1, 0).getDate(); $("#calendar-month").textContent = new Intl.DateTimeFormat("de-DE", { month: "long", year: "numeric" }).format(shownMonth); $("#calendar-grid").innerHTML = Array.from({ length: firstDay + days }, (_, index) => { if (index < firstDay) return "<span></span>"; const day = index - firstDay + 1; const date = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; const isToday = date === todayIso; const isSelected = date === selectedDate; const status = day < 11 ? (day % 4 === 0 ? "partial" : "perfect") : isToday ? "partial" : ""; return `<div class="calendar-day current ${isToday ? "today" : ""} ${isSelected ? "selected" : ""}" data-date="${date}">${day}${status ? `<span class="day-status ${status}"></span>` : ""}</div>`; }).join(""); $("#calendar-grid").querySelectorAll("[data-date]").forEach((day) => day.addEventListener("click", () => setSelectedDate(day.dataset.date))); }
async function searchBlsFoods(query) { if (!remoteMode || !supabaseClient) return []; const { data, error } = await supabaseClient.from("food_catalog").select("source_reference,name,brand,category,nutrient_basis,calories_per_100g,protein_per_100g,carbs_per_100g,fat_per_100g,fiber_per_100g,reference_text").eq("source", "BLS 4.0").ilike("name", `%${query}%`).limit(18); if (error) return []; return (data || []).map((item) => ({ id: `bls-${item.source_reference}`, name: item.name, brand: item.brand, category: item.category || "all", meal: "Snack", calories: Math.round(item.calories_per_100g || 0), protein: Number(item.protein_per_100g || 0), carbs: Number(item.carbs_per_100g || 0), fat: Number(item.fat_per_100g || 0), fiber: Number(item.fiber_per_100g || 0), emoji: "🥗", portion: item.nutrient_basis, nutrientBasis: item.nutrient_basis, source: "BLS 4.0", reference: item.source_reference, referenceText: item.reference_text })); }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 2200); }
function editGoal() { const nextGoal = Number(window.prompt("Wie viele Kalorien möchtest du täglich anpeilen?", goal)); if (nextGoal >= 500 && nextGoal <= 10000) { goal = Math.round(nextGoal); localStorage.setItem("nutrify-goal", goal); if (remoteMode) supabaseClient.from("profiles").update({ daily_goal: goal }).eq("id", currentUser.id); renderDashboard(); renderWeek(); showToast("Tagesziel aktualisiert"); } }
function openLog(foodId) { if (isPastDate(selectedDate)) return showToast("Vergangene Tage können nicht bearbeitet werden"); const select = $("#food-select"); select.innerHTML = foods.map((food) => `<option value="${food.id}" ${String(food.id) === String(foodId) ? "selected" : ""}>${food.emoji} ${food.name}</option>`).join(""); $("#food-amount").value = 100; updateDialogCalories(); $("#log-dialog").showModal(); }
function selectedAmountInGrams(food) { const amount = Number($("#food-amount").value || 0); const unit = $("#food-unit").value; return unit === "piece" ? amount * (food.pieceWeight || 50) : amount; }
function updateDialogCalories() { const food = foods.find((item) => String(item.id) === String($("#food-select").value)); if (food) $("#dialog-calories").textContent = `${Math.round(food.calories * selectedAmountInGrams(food) / 100)} kcal`; }
function openAccount() { $("#account-status").textContent = ""; $("#account-dialog").showModal(); }
function addCustomFood(event) { event.preventDefault(); const name = $("#custom-food-name").value.trim(); const brand = $("#custom-food-brand").value.trim(); const calories = Number($("#custom-food-calories").value); if (!name || calories < 0) return; const food = { id: `custom-${Date.now()}`, name, brand, calories, category: "all", meal: "Snack", emoji: "🍽️", portion: "Eigenes Lebensmittel · pro 100 g" }; foods.push(food); $("#custom-food-dialog").close(); $("#custom-food-form").reset(); openLog(food.id); showToast("Eigenes Lebensmittel hinzugefügt"); }
$("#setup-form").addEventListener("submit", async (event) => { event.preventDefault(); const rawUrl = $("#supabase-url").value.trim(); const key = $("#supabase-key").value.trim(); if (!rawUrl || !key) return setAuthMessage("Bitte URL und Key eingeben.", true); try { const parsedUrl = new URL(rawUrl); if (parsedUrl.protocol !== "https:") return setAuthMessage("Die Supabase-URL muss mit https:// beginnen.", true); const url = parsedUrl.origin + parsedUrl.pathname.replace(/\/$/, ""); localStorage.setItem("nutrify-supabase-url", url); localStorage.setItem("nutrify-supabase-key", key); supabaseClient = window.supabase.createClient(url, key); const { data, error } = await supabaseClient.auth.getSession(); if (error) return setAuthMessage("Supabase-Fehler: " + error.message, true); if (data.session) return enterApp(data.session.user); showLogin("Verbindung erfolgreich. Jetzt kannst du dich einloggen."); } catch (error) { console.error(error); setAuthMessage("Verbindungsfehler: " + (error?.message || error), true); } });
$("#auth-form").addEventListener("submit", async (event) => { event.preventDefault(); const email = $("#auth-email").value.trim(); const password = $("#auth-password").value; const result = authModeLogin ? await supabaseClient.auth.signInWithPassword({ email, password }) : await supabaseClient.auth.signUp({ email, password, options: { emailRedirectTo: window.location.origin } }); if (result.error) return setAuthMessage(friendlyAuthError(result.error), true); if (!authModeLogin && result.data.session) return enterApp(result.data.session.user); setAuthMessage(authModeLogin ? "Anmeldung läuft ..." : "Konto erstellt. Öffne deine E-Mail und bestätige den Link. Danach landest du wieder bei NUTRIFY."); });
$("#auth-switch").addEventListener("click", () => { authModeLogin = !authModeLogin; $("#auth-title").textContent = authModeLogin ? "Willkommen zurück." : "Dein NUTRIFY-Konto."; $("#auth-submit").textContent = authModeLogin ? "Einloggen" : "Konto erstellen"; $("#auth-switch").textContent = authModeLogin ? "Noch kein Konto? Jetzt registrieren" : "Bereits registriert? Einloggen"; });
$("#reset-config").addEventListener("click", () => { localStorage.removeItem("nutrify-supabase-url"); localStorage.removeItem("nutrify-supabase-key"); showSetup(); }); $("#profile-button").addEventListener("click", openAccount); $("#cancel-account").addEventListener("click", () => $("#account-dialog").close()); $("#cancel-log").addEventListener("click", () => $("#log-dialog").close()); $("#open-custom-food").addEventListener("click", () => { $("#log-dialog").close(); $("#custom-food-dialog").showModal(); }); $("#cancel-custom-food").addEventListener("click", () => $("#custom-food-dialog").close()); $("#custom-food-form").addEventListener("submit", addCustomFood); $("#logout-button").addEventListener("click", () => supabaseClient.auth.signOut()); $("#quick-entry-submit").addEventListener("click", runQuickEntry); $("#quick-entry-input").addEventListener("keydown", (event) => { if (event.key === "Enter") runQuickEntry(); }); $("#calculate-goal").addEventListener("click", calculateGoal); $("#open-goal-setup").addEventListener("click", () => { $("#account-dialog").close(); $("#goal-dialog").showModal(); calculateGoal(); }); $("#cancel-goal").addEventListener("click", () => $("#goal-dialog").close()); $("#cancel-recipe").addEventListener("click", () => $("#recipe-dialog").close()); $("#new-recipe").addEventListener("click", () => $("#recipe-dialog").showModal()); $("#recipe-form").addEventListener("submit", (event) => { event.preventDefault(); const recipes = JSON.parse(localStorage.getItem("nutrify-recipes") || "[]"); recipes.push({ name: $("#recipe-name").value.trim(), ingredients: $("#recipe-ingredients").value.trim(), calories: Number($("#recipe-calories").value) }); localStorage.setItem("nutrify-recipes", JSON.stringify(recipes)); $("#recipe-form").reset(); $("#recipe-dialog").close(); renderRecipes(); showToast("Rezept gespeichert"); }); $("#toggle-favorite").addEventListener("click", () => toggleFavorite($("#food-select").value)); $("#show-favorites").addEventListener("click", () => { const favorites = JSON.parse(localStorage.getItem("nutrify-favorites") || "[]"); if (!favorites.length) return showToast("Noch keine Favoriten gespeichert"); $("#food-search").value = ""; $("#food-grid").innerHTML = foods.filter((food) => favorites.includes(String(food.id))).map((food) => `<article class="food-card"><div class="food-card-top"><span class="food-emoji">${food.emoji}</span><button class="food-add" data-food-id="${food.id}">+</button></div><h3>${food.name}</h3><p>${food.portion}</p><strong>${food.calories} <small>kcal</small></strong></article>`).join(""); document.querySelectorAll(".food-add").forEach((button) => button.addEventListener("click", () => openLog(button.dataset.foodId))); });
$("#account-form").addEventListener("submit", async (event) => { event.preventDefault(); const displayName = $("#account-name").value.trim(); if (!displayName) return $("#account-status").textContent = "Bitte einen Benutzernamen eingeben."; localStorage.setItem("nutrify-display-name", displayName); $("#profile-name").textContent = displayName; if (remoteMode) { const result = await supabaseClient.from("profiles").upsert({ id: currentUser.id, display_name: displayName, daily_goal: goal }); if (result.error) { $("#account-status").textContent = `Lokal gespeichert. Online-Sync fehlgeschlagen: ${result.error.message}`; $("#account-dialog").close(); showToast("Profil lokal gespeichert"); return; } } $("#account-dialog").close(); showToast("Profil gespeichert"); });
document.querySelectorAll("[data-view], [data-view-link]").forEach((element) => element.addEventListener("click", () => { const view = element.dataset.view || element.dataset.viewLink; document.querySelectorAll(".view").forEach((item) => item.classList.remove("active-view")); $(`#${view}-view`).classList.add("active-view"); document.querySelectorAll(".nav-item").forEach((item) => item.classList.toggle("active", item.dataset.view === view)); $("#page-title").textContent = view === "dashboard" ? "Dein Überblick" : view === "calendar" ? "Dein Kalender" : "Lebensmittel finden"; }));
document.querySelectorAll("[data-open-log]").forEach((element) => element.addEventListener("click", () => openLog()));
$("#log-form").addEventListener("submit", async (event) => { event.preventDefault(); const food = foods.find((item) => String(item.id) === String($("#food-select").value)); const inputAmount = Number($("#food-amount").value); const amount = food ? selectedAmountInGrams(food) : 0; const meal = $("#meal-select").value; if (!food || !inputAmount || inputAmount < 1) return showToast("Bitte Lebensmittel und Menge prüfen"); const localEntry = { foodId: food.id, amount, meal, food, date: selectedDate }; allEntries.push(localEntry); entries = allEntries.filter((entry) => entry.date === selectedDate); saveEntries(); renderDashboard(); renderWeek(); renderDaySummary(); $("#log-dialog").close(); showToast("Eintrag gespeichert"); if (remoteMode) { try { await saveRemoteEntry(food, amount, meal); } catch { pendingEntries.push({ food, amount, meal, date: selectedDate }); localStorage.setItem("nutrify-pending-entries", JSON.stringify(pendingEntries)); setSyncStatus("offline", "Offline gespeichert"); showToast("Online-Sync folgt automatisch"); } } });
$("#food-select").addEventListener("change", updateDialogCalories); $("#food-amount").addEventListener("input", updateDialogCalories); $("#food-search").addEventListener("input", () => { renderFoods(); clearTimeout(window.foodSearchTimer); window.foodSearchTimer = setTimeout(searchOnlineFoods, 450); }); $("#food-category").addEventListener("change", renderFoods); $("#edit-goal").addEventListener("click", editGoal); $("#previous-day").addEventListener("click", () => shiftSelectedDate(-1)); $("#next-day").addEventListener("click", () => shiftSelectedDate(1)); $("#today-button").addEventListener("click", () => setSelectedDate(todayIso)); $("#selected-date").addEventListener("change", (event) => setSelectedDate(event.target.value || todayIso)); $("#prev-month").addEventListener("click", () => { shownMonth.setMonth(shownMonth.getMonth() - 1); renderCalendar(); }); $("#next-month").addEventListener("click", () => { shownMonth.setMonth(shownMonth.getMonth() + 1); renderCalendar(); });
$("#food-unit").addEventListener("change", updateDialogCalories); $("#save-calculated-goal").addEventListener("click", () => { const value = Number($("#calculated-goal").textContent.replace(/[^0-9]/g, "")); if (value) { goal = value; localStorage.setItem("nutrify-goal", goal); if (remoteMode) supabaseClient.from("profiles").update({ daily_goal: goal }).eq("id", currentUser.id); renderDashboard(); renderWeek(); $("#goal-dialog").close(); showToast("Kalorienziel gespeichert"); } });
$("#sync-status").addEventListener("click", async () => { if (!remoteMode) return showToast("Bitte zuerst einloggen"); setSyncStatus("syncing", "Synchronisiere ..."); try { await loadRemoteData(); if (await syncPendingEntries()) await loadRemoteData(); showToast("Synchronisierung abgeschlossen"); } catch { setSyncStatus("offline", "Offline gespeichert"); showToast("Verbindung noch nicht verfügbar"); } });
$("#food-search").addEventListener("input", async () => { const query = $("#food-search").value.trim(); if (query.length < 3) return; const blsFoods = await searchBlsFoods(query); if (blsFoods.length) { foods = [...blsFoods, ...foods.filter((food) => !String(food.id).startsWith("bls-"))]; renderFoods(); } });
window.addEventListener("online", () => { if (remoteMode) { setSyncStatus("syncing", "Verbindung wird geprüft ..."); loadRemoteData().then(() => syncPendingEntries()).then(() => showToast("Verbindung wieder aktiv")).catch(() => setSyncStatus("offline", "Offline gespeichert")); } });
window.addEventListener("offline", () => setSyncStatus("offline", "Offline gespeichert"));
$("#summary-dashboard").addEventListener("click", () => { document.querySelectorAll(".view").forEach((item) => item.classList.remove("active-view")); $("#dashboard-view").classList.add("active-view"); $("#page-title").textContent = "Dein Überblick"; });
renderDashboard(); renderWeek(); renderFoods(); renderRecipes(); renderCalendar(); setSelectedDate(todayIso); renderDaySummary(); initialiseAuth().catch((error) => { showSetup(); setAuthMessage(`Verbindung fehlgeschlagen: ${error.message}`, true); });
