create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  daily_goal integer not null default 2000,
  created_at timestamptz not null default now()
);

create table if not exists public.food_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  food_name text not null,
  food_brand text,
  product_code text,
  data_source text,
  data_reference text,
  nutrient_basis text not null default 'pro 100 g',
  calories_per_100g integer not null,
  protein_per_100g numeric,
  carbs_per_100g numeric,
  fat_per_100g numeric,
  amount_grams integer not null check (amount_grams > 0),
  meal text not null,
  eaten_on date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.food_catalog (
  id bigint generated by default as identity primary key,
  source text not null,
  source_reference text not null,
  name text not null,
  brand text,
  category text,
  nutrient_basis text not null default 'pro 100 g',
  calories_per_100g numeric,
  protein_per_100g numeric,
  carbs_per_100g numeric,
  fat_per_100g numeric,
  fiber_per_100g numeric,
  reference_text text,
  created_at timestamptz not null default now(),
  unique (source, source_reference)
);

create index if not exists food_catalog_name_search on public.food_catalog using gin (to_tsvector('simple', name));

alter table public.profiles enable row level security;
alter table public.food_entries enable row level security;
alter table public.food_catalog enable row level security;
drop policy if exists "Users manage own profile" on public.profiles;
drop policy if exists "Users manage own entries" on public.food_entries;
create policy "Users manage own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "Users manage own entries" on public.food_entries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Anyone can read food catalog" on public.food_catalog;
create policy "Anyone can read food catalog" on public.food_catalog for select using (true);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Erstellt Profile für Konten, die bereits vor dem Schema existiert haben.
insert into public.profiles (id)
select id from auth.users
on conflict (id) do nothing;

-- Falls die Tabellen bereits existieren, ergänzt dieser Teil die neuen Felder.
alter table public.profiles add column if not exists display_name text;
alter table public.food_entries add column if not exists food_brand text;
alter table public.food_entries add column if not exists product_code text;
alter table public.food_entries add column if not exists data_source text;
alter table public.food_entries add column if not exists data_reference text;
alter table public.food_entries add column if not exists nutrient_basis text not null default 'pro 100 g';
alter table public.food_entries add column if not exists protein_per_100g numeric;
alter table public.food_entries add column if not exists carbs_per_100g numeric;
alter table public.food_entries add column if not exists fat_per_100g numeric;